### ISSUE TITLE
not syncing

### ISSUE THREAD

**Issue by exekutive** [marcelklehr/floccus#109]
I noticed that some bookmarks were missing in Nextcloud, so I checked floccus. It says the last sync was two weeks ago. I didn't make any changes two weeks ago (but I may have upgraded Nextcloud.)

I started troubleshooting by clicking the 'run tests' button. The tests were successful, but now floccus is hung up. I just get a blank bubble whenever I click the floccus icon. Even if I disable/enable the addon. Restarting Firefox didn't help.

Firefox 60
Floccus 2.2.3

**Comment by exekutive** [comment]
OK Thanks. Any ideas why floccus stopped sycing my bookmarks?

**Comment by marcelklehr** [comment]
Mh. No ideas come to mind. I'd have to see a log file. Does it sync again, now?

**Comment by marcelklehr** [comment]
Sorry, my bad.

#### Firefox
* Go to `about:debugging`
* enable debugging
* click on `debug` button next to floccus entry
* in the inspector window copy the logs

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* in the inspector window copy the logs

**Comment by elrido** [comment]
Hi, I have very similar issues since about 1 - 2 weeks. Floccus (Firefox) shows me as status "Syncing...", the "Sync now" button is disabled. I did run the debugging as described above and get this in the inspector:

Content Security Policy: Die Einstellungen der Seite haben das Laden einer Ressource auf self blockiert ("script-src"). Source: ;undefined.

I checked the CSP header of my Nextcloud 13.0.2.1 instance and it is this:
Content-Security-Policy: default-src 'none';base-uri 'none';manifest-src 'self'

If it is a reasonable assumption that CSP is blocking floccus, I'll be glad to temporarily turn it off to test this, but longer term I would of course prefer a better solution. Maybe there is an exception that we would need to add?

**Comment by marcelklehr** [comment]
@elrido Deleting the account and re-creating it should fix this. It can get stuck in sync, when the browser is closed while it's syncing. I'm working on a fix.

**Comment by exekutive** [comment]
It's back to normal for me. I'm not sure what happened.

**Comment by marcelklehr** [comment]
@xelcho Thanks :) 500 means there was an error on the server-side. The nextcloud log might know more on why you got a 500 Response. Please open a new issue if the problem persists :)

I'm closing this issue now as the original poster doesn't seem to have the problem anymore and the title apparently attracts people with unrelated issues... :D
