### ISSUE TITLE
User Interface > Server Path - what does this mean?

### ISSUE THREAD

**Issue by davelcpanelnet** [marcelklehr/floccus#124]
### Software versions

* Browser: FireFox 61.0b12
* Nextcloud: 13.0.2
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.2.7

### Steps to reproduce

The steps here are simply ambiguity on what this field is _doing_.  

I love this app and would love to closely QA the work and collaborate!  It's wonderful and I appreciate the hard work - especially the move toward WebDav that you are doing with Julian ( I work with him ).

![screenshot 2018-06-08 at 1 25 01 pm](https://user-images.githubusercontent.com/5264762/41174426-bb5e8622-6b1f-11e8-91b6-cee8296453c9.png)

**Comment by marcelklehr** [comment]
Thanks for you kind words :)

The server path can be specified to sync the bookmarks in the sync folder to a sub directory on the server. This allows you to sync across browsers as syncing the root directory between firefox and chrome doesn't work since their root folders are named differently. With this option you can setup two accounts: One for the "bookmarks bar" sub dir and one for an "other bookmarks" sub dir on the server and map a local folder to those. I hope that explanation makes sense. If you have the time and can explain this better, I'd be glad to see a pull request that adds this to the README :)

**Comment by bernd-wechner** [comment]
Alas I'm trying to read this and not following. Some clarification of "local folder" and what it means to map it to a sub dir on the server. I think it might be very helpful have a clear worked example of what's meant here. Admittedly I am one of the presumably many, disillusioned Xmarks users out there hoping to achieve similar (which was to see the same bookmarks across browsers and devices). I'm trying to understand this issue in no small part because of that history (in fact I have identical bookmarks in Chrome and Firefox on different machines and want try and see them syncing again. 

From what I read here marcel, you are suggesting a setup that would achieve it.  A mapping of "bookmarks bar" subdir to a local folder for example, now I only have to understand what that means and how to set it up ... alas it means little to me :-(.

**Comment by marcelklehr** [comment]
@bernd-wechner Thank you for your feedback. I have admittedly been immersed in development lately, so much that I have neglected documentation to some extend. Let me explain it more thoroughly (And hopefully this can be put into the README as well, if it is understandable :D):

## Syncing across browser vendors
It is possible to sync a single bookmark folder in  e.g. your firefox with another folder in e.g. your Chrome instance without any further hassle: Setup the account in floccus. In the account options you can select the bookmark folder to be synced with the server. Done.

### Syncing the root folder across browsers
Syncing the root folder of your bookmarks between e.g. firefox and chrome is a bit harder because the main folders (e.g. 'Bookmarks toolbar', 'Other Bookmarks', etc.) are named differently in both browsers. Thus, when you sync the root folder directly, the folders cannot be merged because they are named differently.

You can however, specify a 'server path' in your account. This is like the target folder of a copy or rsync command. While the sync folder you have selected from your browser bookmarks normally will end up being synced to the root path on your server, you can change that to an arbitrary path / sub-directory, e.g. `/Toolbar`.

Now, you can setup multiple floccus accounts per browser. One for each main bookmarks folder you'd like to sync. You can, for example, create an account,set the server path to `/Toolbar` and select `/Bookmarks Toolbar` as the folder to sync in the account options. If you want to sync `Other bookmarks` to, you can create a new account with the same credentials, select `/Other Bookmarks` in the options, but this time you specify a different path in 'server path' , e.g. `/Others`.

Does that make sense?

**Comment by davelcpanelnet** [comment]
That adds a great deal of clarity to me!  Thank you, Marcel!

If you have any branches you would like active QA work done on - I would be more than happy to lend a hand!

**Comment by bernd-wechner** [comment]
Thanks Marcel, that is better, and no need to apologize, I know exactly how it feels. And am happy like Dave to lend a hand if I can. Alas low on skills in the area of add-ons.

What is still a little unclear for me is what you mean a bookmark folder. If I take a guess I would say that then I press CTRL+SHIFT+O in Firefox I get a manager like this:

![image](https://user-images.githubusercontent.com/7296506/41559837-a982148e-7388-11e8-9c57-99fee44dba33.png)

And that by bookmark folder you mean:

All Bookmarks
Bookmarks Toolbar
Bookmarks Menu
Other Bookmarks

and of course any that appear under those as it's a hierarchy. 

In Chrome I also can press CTRL+SHIFT+O and see a hierarchy of Bookmarks this time with two entries:

Bookmarks Bar
Other bookmarks

and beneath those a hierarchy of bookmarks.

I wonder what "root folder" means. Perhaps Root folder is in each of the above cases you mean All Bookmarks in Firefox and the  unnamed container of Bookmarks Bar and Other bookmarks in Chrome?

And so I'm starting to guess that:

On Firefox:
Server Path: /Toolbar
Sync Folder: Bookmarks Toolbar

On Chrome:
Server Path: /Toolbar
Sync Folder: Bookmarks Bar

would see the bookmarks toolbar sync between the two browsers and

On Firefox:
Server Path: /Menu
Sync Folder: Bookmarks Menu

On Chrome:
Server Path: /Menu
Sync Folder: Other bookmarks

would see the menus sync ...?

Am I understanding it right now?

**Comment by marcelklehr** [comment]
@bernd-wechner Yep, exactly right :)

**Comment by bernd-wechner** [comment]
Cool. Minor suggestions then for newbs is change the label "Sync folder" to "Bookmark folder to sync" and to group the Sync folder and Server path options on the interface so they are a pair in the form:

Bookmark folder to sync:
Server path to store it in:

Just a thought.

**Comment by marcelklehr** [comment]
I've updated the README to contain a part of this explanation.
