### ISSUE TITLE
Can't sync on Chromium 67

### ISSUE THREAD

**Issue by andreas-bulling** [marcelklehr/floccus#126]
Hi,

I am trying to sync my bookmarks on Chromium 67 but see the following error message:

`Invocation of form bookmarks.getSubTree(undefined, function) doesn't match definition bookmarks.getSubTree(string id, function callback)`

**Comment by marcelklehr** [comment]
Hi Andreas,

has it worked for you before? Did a Chromium update change things? Are you trying to sync a specific folder?

**Comment by marcelklehr** [comment]
So, you're trying to sync the root folder with the collection synced from the root folder in firefox?

**Comment by marcelklehr** [comment]
In order to sync across browsers from different vendors, you'll need to create separate accounts for each of the root folders in your browser, as these are named differently in Chrome and Firefox. You will need to set a separate server path for each account for the bookmarks of the two not to collide.

**Comment by andreas-bulling** [comment]
Hm, strange - suddenly it worked without problems and even without creating a separate server path?!

**Comment by marcelklehr** [comment]
Very strange, indeed. I'm closing this for now. Let me know if you have trouble again.
