### ISSUE TITLE
please specify how to disable the native sync

### ISSUE THREAD

**Issue by DJCrashdummy** [marcelklehr/floccus#129]
i know, that the built in sync should be disabled as it is stated in the [readme](https://github.com/marcelklehr/floccus#install):

> [...] not enable native bookmark synchronization built into your browser, [...]

and also at [AMO](https://addons.mozilla.org/firefox/addon/floccus/):

> [...] with Sync disabled!

but please can you explain in detail how this could be accomplished, even if one or more `about:config` entries have to be changed...

i have looked a little bit around (in firefox) and no idea what to do:
- at the normal settings there is nothing else than sign up or sign in
- and at the `about:config` there are a ton of settings regarding `sync` and still a bunch of potential settings to disable something about (bookmark) sync like `webextensions.storage.sync.enabled`, `services.sync.engine.bookmarks`, etc... but i haven't tried any of them, to not break something. :confused:

**Comment by marcelklehr** [comment]
Hey :)

In the default state firefox sync is disabled, so unless you have setup your firefox account, you're safe. If you have setup a firefox account already, this should help you out: https://support.mozilla.org/en-US/questions/1076587

**Comment by DJCrashdummy** [comment]
@marcelklehr thank you very much for your quick reply!

may i suggest to add a few words to both addon-stores (at chrome it is also just stated _"[...] with Google Sync disabled."_) and the readme to avoid similar questions in future. ...or if it is valid in both cases at least use a more precise wording, like **_"[...] with sync account disabled!"_**.

**Comment by DJCrashdummy** [comment]
...or maybe it is just me thinking about this possibility, because the first thing i do after creating a new firefox-profile (even before doing some setting or installing addons) is opening the `about:config` and changing `extensions.pocket.enabled` to `false`. :wink:

**Comment by hg42** [comment]
I came here to github to ask exactly the question of this issue.
Above you talk about disabling the complete Firefox sync.

I can
* disable sync completely ("Disable" button at sync account, which I don't want because of the other items)
* I can uncheck bookmarks sync alone

But, I can imagine other problems, e.g. syncing add-on data may conflict, if the state of the sync is kept there?
In this case it should better be kept somewhere else.

Btw. @DJCrashdummy, what is the relation to pocket?

**Comment by DJCrashdummy** [comment]
> what is the relation to pocket?

pretty much nothing... the only relation to [pocket](https://en.wikipedia.org/wiki/Pocket_(service)) is, that it is a company owned by the Mozilla Corporation.
and i deactivate it at the very beginning, because i'm not interested in proprietary services (_who knows what happens with my data?_) and its preinstalled addons (_probably uses resources, even i never needed and will never need it._).

**Comment by hg42** [comment]
ok, I had the impression, FF sync would (at least sometimes) sync add-on preferences, but these might result from being stored in prefs.js

I am using several firefox, chrome, chromium versions on several computers and smartphones on linux, windows 10, android, which means I desperately need all kinds of sync.

I prefer open source  and cross-platform, but it is difficult to keep up with all the new developments in browsers or web sites.
E.g. once I used XMarks and it worked really well, but then they were bought up and now they are gone.
At the time they were bought, I switched to firefox sync. But this doesn't help me with my chrome type browsers.

I always tried to become independent from google etc. not because of privacy concerns (google has always done great things for me and never bothered me since I first used their search engine in altavista times). But I want open source, which is generally better for users (a lot of reasons). At the end this didn't work enough and I stayed with google (but still hate facebook, whatsapp etc. despite having to use them).

Now, firefox showed a different problem. I am definitely not main stream enough and my goals don't fit well with theirs. So they removed a lot of possibilities for add-ons and now firefox is very similar to chrome. I would use only chrome like browsers (or better chromium like), IF there were good solutions for tree style tabs, which are mandatory for me, no way to manage all my tabs horizontally and without a dependency tree.

So currently, I am hopping between browsers, each missing one or the other feature.

I am also revisiting the whole independance topic.
I am trying my own home server (pi + dyndns) with NextCloud etc.
But there are still several things missing...

Sync is one of them and I am currently trying different solutions, e.g. floccus.

**Comment by DJCrashdummy** [comment]
FWIW since firefox 60 there is an `about:config` setting to disable firefox accounts resp. firefox sync: just set `identity.fxaccounts.enabled` (you may open `about:config?filter=identity.fxaccounts.enabled` in the adressbar) to `false`... a restart of firefox may be required to complete the process.

**Comment by marcelklehr** [comment]
AFAIR, not having your browser sync your bookmarks in addition to floccus should be fine. However, you achieve that.
