### ISSUE TITLE
Reset cache: Explicitly select which side to keep or whether to merge

### ISSUE THREAD

**Issue by jlbprof** [marcelklehr/floccus#169]
I do not believe there is a way to do this now, so correct me if I am wrong.

I am looking at the recent option you added "reset cache".  I am not totally sure what that is intended to do so let me explain one of the features I liked from Xmarks.

You could select normal syncing, or you could say keep what is on the server and throw away what is on the browser, or you could say keep what is on the browser and throwaway what is on the server.

I believe "reset cache" is probably equivalent to "keep what is on the browser, and throw away what is on the server".

So am I correct in what "reset cache" does?

What do you think about the other options I listed? 

Right now if I want to throw away what is on the browser, I have to first delete my local bookmarks and then sync.   Or if I want what is on the browser, I would delete my bookmarks.xbel file on the server and sync.

Thanx

Julian

**Comment by marcelklehr** [comment]
> I believe "reset cache" is probably equivalent to "keep what is on the browser, and throw away what is on the server".

Not quite. Reset cache causes floccu to sync from scratch the next time, merging both server and browser. If you*only* want to keep the local bookmarks, delete the ones on the server and reset the cache (so that the already linked local bookmarks won't get removed, too, on the next sync). And vice versa if you *only* want to keep the server bookmarks.

The functionality you lay out would be a nice to have, IMO, as you can emulate it with the features already available, but it shouldn't be too hard to clear the browser/server before syncing if the user selects that I'm thinking, it could be a dropdown after the reset cache option.

Do you want to give it a try? :)

**Comment by jlbprof** [comment]
I may look into it, thanx Marcel

**Comment by raxetul** [comment]
Also better to rename "Reset" option as "Merge" and it should be acivated by default to keep user on the safe side. "Reset" makes people think it will reset all bookmarks and resync and with the "Tick this box to ...... local bookmarks together" explanation it is confusing.

**Comment by marcelklehr** [comment]
@raxetul Thanks for the input! Renaming the option definitely makes sense. I think activating the merge/reset option by default is not a good idea, because deletions will not be propagated if this is the case.

**Comment by marcelklehr** [comment]
Closing in favor of #244, which is essentially the same, I think.

**Comment by marcelklehr** [comment]
Feel free to try our this feature in the [latest beta](https://github.com/marcelklehr/floccus/issues/338)
