### ISSUE TITLE
keyword search broken because floccus changes "%s" into "%25s" in URLs

### ISSUE THREAD

**Issue by Whissi** [marcelklehr/floccus#172]
### Software versions
* Browser: Mozilla Firefox 62.0 / 62.0.2
* Nextcloud: 14.0.0
* Nextcloud Bookmarks app: 0.13.0
* Floccus: 3.0.8

### Steps to reproduce
1. Create a bookmark like shown:

![bookmark-shortcut-keyword](https://user-images.githubusercontent.com/729436/45918145-b8c8e680-be82-11e8-8036-a68aa00733e9.jpg)

2. Verify that it is working, i.e. when you now type "leo cat" into your address bar and hit enter, Firefox should request `https://dict.leo.org/?search=cat`

3. Now wait until floccus will notice your new bookmark/changes and start synchronizing.

### Expected outcome
I would expect that floccus will sync my changes without changing values.

### Actual outcome
Floccus changes URL from `https://dict.leo.org/?search=%s` into `https://dict.leo.org/?search=%25s` which breaks keyword search.

**Comment by marcelklehr** [comment]
Hello there,
thanks for taking the time to give feedback. Regarding your issue: floccus actually doesn't change values, but nextcloud bookmarks normalizes the URLs in order to find duplicates more easily. In your case, `%s` is actually not a valid URI component and is thus normalized by encoding `%` into `%25`. When I enter `https://dict.leo.org/?search=%25s` in my URL bar, leo searches for `%s`. What did you expect?

**Comment by Whissi** [comment]
Please note that this is a special URL. Firefox will replace "%s" with the string I enter after the keyword.
My expectation is that nothing will mess with the URL value the user has set. :)

**Comment by marcelklehr** [comment]
Alright, so I've decided not to fix this, because

- I don't want to sacrifice duplicate detection for being able to deal with invalid URLs
- It would have been possible on mozilla's part to design the feature in a way that would not leave invalid URLs
- It is possible to work around this by not syncing with the bookmarks app, but with WebDAV/XBEL.
- It is possible to get the same behavior while still syncing with the bookmarks app, with the standard search engine settings: https://support.mozilla.org/en-US/kb/add-or-remove-search-engine-firefox

The only downside to the latter is that you cannot sync those via floccus at the moment. I know this is probably not ideal for you. In any case, thank you for your feedback! :)
