### ISSUE TITLE
Compatibility with Firefox 47

### ISSUE THREAD

**Issue by e-alfred** [marcelklehr/floccus#2]
Hello,

this nice addon is currently not compatible with Firefox 47, the addons page says. Is it possible to make it compatible with Firefox 47?

**Comment by marcelklehr** [comment]
Yep, I'm using the WebExtension API to be compatible with chrome and that is only available beginning with Fx48, you'll either have to install a beta/nightly version or else wait for v48 to hit stable. Sorry :/

**Comment by e-alfred** [comment]
Okay, I tried it under Firefox 50 and it works well. Do you have information on how to run it in Chromium-based browsers?

**Comment by marcelklehr** [comment]
I'm in the process of trying to make up my mind whether I want to pay $5 to google in order to be able to publish a free extension on their web store... In any case you can [download the floccus zip archive](https://github.com/marcelklehr/floccus/archive/master.zip), rename it to `floccus.crx`, go to [chrome's extension](chrome://extensions/) and install floccus by dragging the crx file onto the extension page.

**Comment by marcelklehr** [comment]
Update: I found out how to do this properly and updated the [install instructions](https://github.com/marcelklehr/floccus#chrome) accordingly. Going to close this for now.
