### ISSUE TITLE
Sync error with WebDAV nextcloud

### ISSUE THREAD

**Issue by piotr5151** [marcelklehr/floccus#220]
### Software versions

- Browser: 70.0.3538.77
- Nextcloud: 13
- Nextcloud Bookmarks app: 0.12.2
- Floccus: 3.2.2
- Floccus sync method: 

### Steps to reproduce

After upgrade to 3.2.2 floccus doesn't sync with webdav. Nextcloud Bookmarks works still perfectly.

### Expected outcome

...

### Actual outcome

...

**Comment by marcelklehr** [comment]
WHat is the error message? And can you provide the debug log (either here, or via email)?

**Comment by piotr5151** [comment]
The error message is: "Error 404. Failed to upload XBEL file. Check your
server configuration." 

W dniu 2019-01-01 20:40, Marcel Klehr napisał(a):

> WHat is the error message? And can you provide the debug log (either here, or via email)? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].
 

Links:
------
[1]
https://github.com/marcelklehr/floccus/issues/220#issuecomment-450752336
[2]

**Comment by marcelklehr** [comment]
Thank you for the log.

I suspect the problem is either of two things: Either the folder on the server doesn't exist (but that's unlikely, as the syncs used to work from what you described), or (more likely) the problem is that the same account was run through the sync operation twice. This shouldn't be happening actually, so I'll investigate some more. Does the error happen consistently? The latter diagnosis would indicate it doesn't occur consistently...

**Comment by marcelklehr** [comment]
Mmh. it shouldn't matter. Are you sure they're not both webdav accounts?

**Comment by jlbprof** [comment]
Did you get the webdav url from the settings page of Nextcloud?   And what
form is your url?

**Comment by marcelklehr** [comment]
I'm using `<nextclouddir>/remote.php/webdav/`

**Comment by piotr5151** [comment]
I replaced the old url by the one copied from nextcloud and it started to sync again.
