### ISSUE TITLE
Chrome shows errors on the extension page

### ISSUE THREAD

**Issue by akidburn** [marcelklehr/floccus#235]
Hi,

Chrome shows errors on the extension page if debuging and error loging for floccus is activated.

for floccus 3.2.6 it shows:

```
   unrecognized manifest key "applications"

   found unexpected key "browser_style"

   syncing failed with

```
and after syncing failed with there is a stacktrace attached.
![image](https://user-images.githubusercontent.com/25623510/53244282-b0cbd780-36aa-11e9-8ac4-cec4aa0d9cd2.png)

Both Chrome and Firefox were way slower since the last update, and cpu usage was higher than normal.
Please fix

akidburn

**Comment by marcelklehr** [comment]
Hey @akidburn 
The warnings are due to cross-browser support. The Error is simply a sync error that is also shown in the UI.

The fact that performance seems to have degraded *could* be due to a recent fix that filters out duplicates that were introduced by an earlier floccus version. I've just commited a patch that should speed up that code a little, but it shouldn't be needed much longer than a few versions, as it basically acts as a kind of migration. The performance drop could also be due to other changes, though :/

**Comment by marcelklehr** [comment]
Has performance improved for you meanwhile?
