### ISSUE TITLE
chrome: Hangs at "Checking..."

### ISSUE THREAD

**Issue by hrehfeld** [marcelklehr/floccus#33]
I can't get the current build of the chrome extension to connect to my server.

I put the following in the account panel:

```
https://mydomain
myuser
mypassword

```
I also tried 

```
https://mydomain/
https://mydomain/index.php/
```

The account panel is also *very* buggy when you add more than one account.

Extension debugging shows nothing (literally nothing).

Google Chrome | 62.0.3202.75 (Official Build) (64-bit)
Bookmarks 0.10.1

**Comment by marcelklehr** [comment]
Hey @hrehfeld,

I'm sorry it doesn't work for you. Regarding extension debugging, you'll need to inspect the options page, instead of the background page. If that's the problem, could you post the redacted console log of the options page?

Thanks for the hint on multi-account usage, I'll check that out.

**Comment by hrehfeld** [comment]
Hmm, for some reason it seems to work after either a chrome restart or debugging the button view (?) No idea, I don't think I changed anything
