### ISSUE TITLE
No sync with NC 12.0.3-3 and FF 57.0

### ISSUE THREAD

**Issue by egeu5** [marcelklehr/floccus#36]
I installed you're addon in my Firefox 57.0 and tested it with NC 12.0.3-3 and Bookmarks 0.10.1. I put in my NC Adress (https://nextcloud.domain.tld) and the username and pw. Nothing happend after a few hours. I did not find any access-tries in the NC-Access logs. A restart of FF did not solve the problem either.

**Comment by marcelklehr** [comment]
Hey,

I'm sorry it doesn't work for you. Have you tried the latest beta version of floccus? (see #27)

**Comment by egeu5** [comment]
Hey,
i tested the beta version. Nice upgraded Account-Add-Interface!
Sometimes it said "Connected" and I can press "Force sync". Somtimes it said "couldn't connect". But there are no bookmarkes synced.
My NC is accesible with IPv6 only. Could that be the reason?

**Comment by marcelklehr** [comment]
Thanks for taking the time to try the beta! :)
It's unlikely that IPv6 is the issue, unless you're unable to access the nextcloud interface with your browser as well.
Could it be that you just haven't found the floccus folder, yet? I've learned from experience that many people fail to find the place where the bookmarks will appear after a sync, so bear with me :)
The floccus folder should be inside the "Other bookmarks" folder, it should be titled "Nextcloud (user@your.nextcloud.tld)".

**Comment by egeu5** [comment]
Tanks for taking the time to build this app ;-) The time I spend to test is a lot of shorter then yours... 
There are no bookmarks at all in my bookmarks app. And I have to look there - or not?

**Comment by marcelklehr** [comment]
The thing is, currently, floccus only syncs bookmarks with nextcloud that are inside the aforementioned folder *in your browser*. It doesn't sync all of the bookmarks in your browser, partly because you might want to have multiple accounts to sync with and also because sadly floccus doesn't support folders, yet. So, the floccus folder should be inside the "Other bookmarks" (or similar) folder in your browser, it should be titled "Nextcloud (user@your.nextcloud.tld)", and putting bookmarks into it should make them appear on the server and vice versa. Don't put folders into it yet, though -- it <del>will eat your dog</del> won't work. ;)

**Comment by egeu5** [comment]
The folder should be titled "Nextcloud (user@https://sub.domain.tld)" for me. Now it is working. Could you do you're sentence 

> the floccus folder should be inside the "Other bookmarks" (or similar) folder in your browser, it should be titled "Nextcloud (user@your.nextcloud.tld)", and putting bookmarks into it should make them appear on the server and vice versa. Don't put folders into it yet

on the landing page of github? It is more clearly :-) Thank you for those plugin and you're immediatiley response!
