### ISSUE TITLE
Feature request: Stop trying to sync without a username and password even entered.

### ISSUE THREAD

**Issue by mannp** [marcelklehr/floccus#40]
Thanks for the plugin, its great, but this niggles me every time I have to setup a new user.

At each point of adding details fail2ban bans the client for repeated incorrect connections, meaning I have to unban and quickly enter the details.

It doesn't make sense for the plugin to try and connect without any details / complete details.

Can the plugin connect when the details are all added, or have it that it starts trying to connect on a force start by the user?

Thanks for your consideration.

**Comment by marcelklehr** [comment]
I've tried to improve the behavior of the automated connectivity check in v1.3.1, so that it waits for the user to pause typing until it checks the credentials. Given that you were apparently still on 1.3.0 when making the comment, I encourage you to try the new version to see if the new behavior is better :)

**Comment by marcelklehr** [comment]
Upon further negative feedback tapping in the same hole, I decided to drop the validation altogether, because nothing will explode if people use the force sync button for testing their account the first time. In fact the validation only tested authentication, but not the whole sync process, so it kinda offers a false security. tl;dr thanks for you sensible advice and happy syncing :)

**Comment by mannp** [comment]
@marcelklehr I personally much prefer you revised method in 1.3.2 👍 thanks for that.

I can add a user and when I am happy with the settings, force a sync.

No more fil2ban resetting.

Keep up the great work :)

**Comment by marcelklehr** [comment]
Thanks :)
