### ISSUE TITLE
import / Export Account configuration function

### ISSUE THREAD

**Issue by eefan000** [marcelklehr/floccus#422]
It's very troublesome to add many accounts again for every browser change

Sharing an account with other people can not directly export a configuration to the other party

**Comment by ItsExtra** [comment]
Is there a way to do this manually? Certainly the configurations are stored in a file somewhere?

Previously I have read that playing around with firefox extension folders can lead to problems which is why I don't want to simply experiment. (I don't know what I'm doing.)

**Comment by marcelklehr** [comment]
**Is your feature request related to a problem? Please describe.**
I run multiple browser on multiple devices, syncing multiple different folder with multiple different teams and it takes quiet some time to setup floccus on all of them without messing up a setting or syncing the wrong folder. Or any of the team members could just mess up.

**Describe the solution you'd like**
Add an export and import function that also allows (optional) to safe the passwords encrypted by providing a password to decrypt the settings file while importing.
It would be helpful to make the settings file editable so that one can change settings in the file before sending it to someone else. 

**Describe alternatives you've considered**
Workarround: Setup every browser and every sync manually on every device. Extremely time consuming.
