### ISSUE TITLE
Hi, is it possible to add Microsoft Edge support ?

### ISSUE THREAD

**Issue by shishixiu** [marcelklehr/floccus#472]

**Comment by marcelklehr** [comment]
Hello @shishixiu 
Thanks for bringing this up. I haven't looked into this in detail, but I think I'm unable to test in Edge because I don't have a windows computer at hand, at the moment. Have you tried installing it from the chrome store? I seem to remember that newer Edge versions use blink under the hood, so it might work out of the box, or shouldn't be too much of a hassle to support. If it doesn't work out of the box yet, some simple debugging to find the error message would go a long way :pray:

**Comment by shishixiu** [comment]
> Hello @shishixiu
> Thanks for bringing this up. I haven't looked into this in detail, but I think I'm unable to test in Edge because I don't have a windows computer at hand, at the moment. Have you tried installing it from the chrome store? I seem to remember that newer Edge versions use blink under the hood, so it might work out of the box, or shouldn't be too much of a hassle to support. If it doesn't work out of the box yet, some simple debugging to find the error message would go a long way 🙏

thank you,I tried it. It's ok!

**Comment by marcelklehr** [comment]
Update: I've submitted the extension to the Edge Extension store and am awaiting their review for publishing.

**Comment by marcelklehr** [comment]
And it's live now. So, now you should be able to get updates seamlessly
