### ISSUE TITLE
Error trying to sync on Firefox 58.

### ISSUE THREAD

**Issue by githubtefo** [marcelklehr/floccus#49]
Hi!
Thank you for your addons, we need it.
I can't synchronize my bookmarks on Firefox 58. I always have the error. I'm using an app password, might be related with that?

Thank you once again!

**Comment by marcelklehr** [comment]
Hello! :)

mmmh. I haven't used 2FA in nextcloud yet, so I haven't been testing it with floccus either. It seems very likely that's the problem. In any case:

In order to aid in debugging, please provide client-side logs. ;)

#### Firefox
* Go to `about:debugging`
* click on `debug` button next to floccus entry
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `force Sync` for the account of your choice.
* go back to the inspector window and copy the logs after waiting approx. 2mins
* paste the logs *somewhere else* removing any sensbile info and link to the site here (e.g. use https://pastebin.com)

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `force Sync` for the account of your choice
* go back to the inspector window and copy the logs after waiting approx. 2mins
* paste the logs *somewhere else* removing any sensbile info and link to the site here (e.g. use https://pastebin.com)

**Comment by githubtefo** [comment]
Now I can sync!
It was a problem related with the address: I should enter https://www.example.server.com/nextcloud**/** instead of https://www.example.server.com/nextcloud
I could figure out thanks to the debugging tool.
Thank you!

**Comment by marcelklehr** [comment]
mmmh. Which version do you have installed? This should be fixed in v1.3.3 :(

**Comment by githubtefo** [comment]
V1.3.3 from Mozilla repositories. Don't worry, may be the showed example in the plugin should contain the "/" at the end.
BTW, the nextcloud application password works!

**Comment by marcelklehr** [comment]
Awesome!

I've just released a new version which now has the fix for the trailing slash problem (which was supposed to land in the last version, *grmbl*).

Thanks for reporting and happy syncing!
