### ISSUE TITLE
Unknown error on a native Chromium-based browser

### ISSUE THREAD

**Issue by LinnyR** [marcelklehr/floccus#512]
**Describe the bug**
foccus works on my chrome, edge, and firefox, but it doesn't work on a native browser called chrome360（Below I have given the URL of this browser）, which is based on Chromium78, and I feel like this plugin works on chrome and should work on this browser. I don't know what the problem is，and I'm not sure what the logs listed below mean. Thanks to the developers.

**To Reproduce**
1. set the webdav.（I'm sure my setup is correct.）
![image](https://user-images.githubusercontent.com/38827394/80855223-fd794e00-8c71-11ea-87f8-28e59da0d40e.png)
2. Click on 'synchronization'
3. See error：Unknown error.

**Screenshots**
![image](https://user-images.githubusercontent.com/38827394/80855027-f9e4c780-8c6f-11ea-9c9f-756b2174000c.png)

**Desktop (please complete the following information):**
 - OS: [Win10 v1909]
 - Browser [https://browser.360.cn/ee/ ]
 - Browser Version [12.0]
 - Floccus version: [4.1.0] 
 - Floccus sync method: [webdav]

**Debug log**
It is often useful to provide a debug log file along with the issue. You can obtain a debug log of the most recent sync runs by clicking 'Debug log' in the bottom right corner of the floccus panel in your browser.

2020-05-02T04:15:12.866Z COMPARE { localItem:   - #360[My IP Address, DNS Leak Test, WebRTC Leak Test, IPv6 Leak Test, HTTP Headers, IP Whois - BrowserLeaks](https://browserleaks.com/ip) parentId: 299,
  cacheItem: null,
  serverItem:   - #364[My IP Address, DNS Leak Test, WebRTC Leak Test, IPv6 Leak Test, HTTP Headers, IP Whois - BrowserLeaks](https://browserleaks.com/ip) parentId: 104 }
2020-05-02T04:15:12.866Z Bookmark unchanged
2020-05-02T04:15:12.867Z onSyncFail

**Comment by marcelklehr** [comment]
I'm not too enthusiastic about debugging an issue that only appears with an exotic browser, but you might be able to find out more about the cause of the issue with the following instructions:

---

In order to aid in debugging, please provide client-side logs.

#### Firefox
* Go to `about:debugging`
* enable debugging
* click on `debug` button next to floccus entry
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `force Sync` for the account of your choice.
* go back to the inspector window and copy the logs after waiting for the sync to finish

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `force Sync` for the account of your choice
* go back to the inspector window and inspect the logs after waiting for the sync to finish
