### ISSUE TITLE
If feasible, this is a feature request: Trigger Import of HTML bookmarks file from Floccus.

### ISSUE THREAD

**Issue by SenaidaHdez** [marcelklehr/floccus#513]
**Describe the solution you'd like**
I would like to see whether it is possible to trigger the import of a HTML bookmarks file  from flocuss. If it was possible, would it be easy to implement? And if it was, I would suggest it as a feature for the future. **Edit: This would allow to get tag support in floccus, as nextcloud bookmark import feature supports tags**

**Describe alternatives you've considered**
At the moment, I am using syncthing to pass my bookmarks locally from laptop to phone. Then, there I use ghost commander whenever I need to find links related to a tag. Once done this and since I am using the firefox synchronization at the moment, I would look for the title of the bookmark in my firefox-based browser. (Firefox Android Browser does not currently support tags either)

**Additional context**
1. It is possible to set up some browsers (like Firefox) to export HTML bookmarks file automatically after closing. In about:config, there is an option called "browser.bookmarks.autoExportHTML" that can be set to true (default=false).
2. Floccus is ~~not syncthing bookmarks at the moment~~ not supporting tags at the moment and Nextcloud Bookmarks (android) does not let me login with my phone. Hoping an update solve any of the issues. Although, Nextcloud Bookmarks doesn't have a searcher for tags and Floccus cannot pass tags at the moment. But I hope they will be able to do it in the future. Fingers crossed.

**Comment by marcelklehr** [comment]
Hello @SenaidaHdez 
Thank you for your feedback.

> Nextcloud Bookmarks does not let me login with my phone

If you are talking about the Bookmarks Android app. We're working to fix that. An update is on the way :)

In general, I'm aware that the user experience on mobile is worse than what could be hoped for, and intend to work on that. :)

**Comment by SenaidaHdez** [comment]
There are two reasons that motivate the import of bookmarks from floccus to nextcloud.
i) Tags are in the html and whenever nextcloud bookmarks imports and html file, it gets the tags. Thus, it would allow to sync tags with nextcloud and one could be independent of firefox sync.
i) Any firefox Android browser does not support tags at the moment, but nextcloud bookmarks android do. Therefore, the only way I could make use of the tag feature in android (for my setup) is to use the android app nextcloud bookmarks.

Thanks for all the work to make bookmarks posible in nextcloud.

Ps: i meant the android nextcloud bookmarks, yes. sorry for not clarifying.

**Comment by marcelklehr** [comment]
Thank you for clarifying your motivation for this request.

Floccus does not support tags currently, because of a fundamental lack of technical support of tags access to browser extensions in firefox and a complete lack of tag support in chrome. Importing and exporting bookmarks files may be a way around that but it comes with its own issues and is fundamentally different from syncing. If floccus supports tags I would want it to be done right.

The android app is thus probably still the best way to use bookmarks (especially with tags) on android -- its maintainer seems to want to put in more time to work on feature parity with the server version. Still, I will put efforts into making the nextcloud bookmarks UI more suitable for mobile use however.
