### ISSUE TITLE
Doubled bookmarks on Chrome mac OS

### ISSUE THREAD

**Issue by aktentasche** [marcelklehr/floccus#57]
Hi,  first of all thanks for this awesome piece of software, been waiting for this ever since I stopped using XMarks ages ago because of privacy concerns.

Floccus runs smooth with my nextcloud account, I am using iridium on Windows and inox on Arch. I recently created another nextcloud account for my girlfriend and installed your extension on Chrome for mac os. The first sync was successful but at some point all bookmarks were doubled locally and floccus shows an error about this. On the server,only single entries exist. I upgraded my nextcloud instance recently but since my own account and browser do not have this issue I suspect it is caused by mac os.

Any ideas?

**Comment by marcelklehr** [comment]
In order to aid in debugging, here's how provide client-side logs.

#### Firefox
* Go to `about:debugging`
* click on `debug` button next to floccus entry
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `Sync now` for the account of your choice.
* go back to the inspector window and copy the logs after waitfor the sync to finish

#### Chrome
* Go to `chrome://extensions`
* enable `Developer mode`
* click on `dist/html/background.html` button in floccus' entry next to "Inspect views: "
* go to floccus options and make sure the account of your choice is connected
* trigger a sync by clicking on `Sync now` for the account of your choice
* go back to the inspector window and copy the logs after waiting for the sync to finish

**Comment by marcelklehr** [comment]
Do you get the same error as #62, now with the latest release? Then I have a fix :)

**Comment by marcelklehr** [comment]
This issue should be fixed in floccus v2.0.2, now. Let me know if this is not the case.

**Comment by aktentasche** [comment]
Marcel, sorry for the late reply. I will follow up on this very soon. 

I could reproduce it btw with inox-bin (Chromium derivative) and Floccus 2.0.0. Is it not possible to sync root any more btw?

**Comment by marcelklehr** [comment]
It is still possible to sync the root folder, but it probably won't work between different browsers, e.g. firefox and chrome. See #69

**Comment by aktentasche** [comment]
Cannot reproduce any more with 2.0.6. neither inox-bin nor mac OS!

Thanks

**Comment by marcelklehr** [comment]
Phew :sweat_smile:  :tada:
