### ISSUE TITLE
Permission to unlimited storage

### ISSUE THREAD

**Issue by prog-amateur2** [marcelklehr/floccus#613]
Hello, I have received a notification to update floccus. 
There is a new permission required to update : Permission to unlimited storage. 

In the Readme and the following [commit](https://github.com/marcelklehr/floccus/commit/a318a74340a741bcb059d7c260571b2dd96c4e50), it is said : 
`storage, unlimitedStorage : Necessary for maintaining a cache and mappings between server and browser bookmarks`

Please, could you explain more in details how does it work (what is exactly store, where exactly, and why) in order to clarify this above sentence ? 

Thank you very much for your kind help.

**Comment by marcelklehr** [comment]
Sure :) 
Floccus stores a snapshot of the last known state of your bookmarks tree as well as an index of which bookmark in your browser is equivalent to which bookmark on the server. This is stored in the browser extension storage. If you only have a few thousand bookmarks the normal storage space will suffice, but since there are people with a lot of bookmarks this space quickly becomes too small, hence the need for unlimited storage.

Floccus will not fill up your hard drive with ever more data. Unless you decide to store a lot more bookmarks everything will stay the same for you.

**Comment by prog-amateur2** [comment]
OK ! I can see much more clearly now, so thank you very much for taking the time to explain it to me in detail. 
For me, it's okay, we can close the issue, I wish you a nice evening !
