### ISSUE TITLE
MySQL

### ISSUE THREAD

**Issue by ThomasRudloff** [marcelklehr/floccus#659]
Hi, is there something like a out of the box solution to use a MySQL server as backend? Actually I do not want to run an HTML or even a cloud server on my network while there is a MySQL8 server already running.

The server is an Odroid H2+ running Oracle Linux. The clients are a Windows XP, a Windows 7 machine and several Raspi 4B running OpenSUSE ARM64 KDE.

How much is the effort to write such an adapter? Is there a template with MySQL server connection where I could put the SQL code in?

Thanks in advance
Thomas

**Comment by marcelklehr** [comment]
Generally it's possible to write new adapters for other backends. I doubt using MySQL as a backend directly is going to work, as floccus can only make http requests.

**Comment by ThomasRudloff** [comment]
Could this be a direction to go?

https://github.com/adamcooke/mysql-http-api

**Comment by ThomasRudloff** [comment]
Found a second one. The first one is really old.

https://www.aceql.com/

**Comment by marcelklehr** [comment]
While I can understand your intentions, I think it would make more sense to focus development efforts on the existing adapters/backends, especially since new adapters have to be maintained as well. Nextcloud bookmarks is already a wrapper around SQL and, while not perfect yet, has a much better user experience than a bare-bones SQL server, IMO. I would encourage you to try it out and perhaps even contribute :heart:

**Comment by marcelklehr** [comment]
You are however welcome to fiddle with this project and add your own adapter for personal use. It's free software after all. Here's the adapters there are so far: https://github.com/marcelklehr/floccus/tree/develop/src/lib/adapters

Cheers! :)
