### ISSUE TITLE
Issue with Syncing Tabs and Bookmarks Root Simultaneously

### ISSUE THREAD

**Issue by simonspa** [marcelklehr/floccus#689]
**Describe the bug**
I'm not entirely sure this qualifies as bug, but it definitely is something that might pose a problem for users. I was really excited to see the tabs sync appear in the recent release notes of floccus 4.4, so I updated and added a new sync to my existing bookmarks root folder sync to also store my tabs. Syncing the tabs up to the server works fine, I have selected a new folder `/Tabs` as target directory.

However, now when trying to sync my bookmarks (root folder, `/`) it apparently also tries to sync the `/Tabs` folder down agan as bookmarks and tells me: "The bookmark root cannot be modified".
I guess it would be good to mention this sort of issue in the "limitations" section of the README? Unless there is an easier way out than not syncing the bookmarks root...

**To Reproduce**
1. Create bookmarks root sync (target: `/`)
2. Sync it - works fine
3. Create tabs sync in addition (target: `/Tabs`)
4. Sync it - works fine
4. Sync bookmarks again - See error

**Expected behavior**
Either it should work (tm) but I don't think that's easily possible, the error message is quite clear, or the limitation should be mentioned in the README or even during setup of the syncs.

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox
 - Browser Version: 81
 - Floccus version: 4.4.0
 - Floccus sync method: nextcloud

**Server (please complete the following information):**
 - OS: Debian 10
 - Nextcloud version: 19.0.4
 - Bookmarks app version: 3.4.4

**Comment by simonspa** [comment]
There seems to be more going on... I realized, inside my `/Tabs` folder mentioned above I have another folder without name, and only therein my tabs:

![image](https://user-images.githubusercontent.com/1677436/96408626-2f607b80-11e4-11eb-9ab0-0077428f9cee.png)

So I thought "hm, let's just try to sync the tabs to `/` then and see if there is some magic going on - but that resulted in the sync running veeery long (several minutes) before I interrupted it. Any hints what to look for?

**Comment by marcelklehr** [comment]
Tab sync is still experimental, but a way to make this work in your case, would be to sync the bookmark root to a sub folder on your server, or sync the tabs via webdav.

**Comment by simonspa** [comment]
Alright, thanks for the feedback! I have noticed that for me, tabs I have recently closed reappear through the sync quite often... For now I switched off automatic sync and just push them manually once in a while. Maybe this could done when closing the browser for example?

**Comment by marcelklehr** [comment]
You can also set the sync strategy to always push, if that's what you want.

**Comment by simonspa** [comment]
I'll have to think about what I actually want to be honest... :rofl: For now I was just playing with a cool new feature! Thanks a lot!

**Comment by marcelklehr** [comment]
Personally, I also think turning automatic sync off and just pushing and pulling manually is quite useful.

**Comment by mmalisz** [comment]
Hi all.

I've got the same issue. It started with the "The bookmark root cannot be modified" message, but I've disabled the auto sync, restarted browser, forced - pushed and everithing was fine.

However after I've tried to pull, I get a new error: "Nextcloud API error: {"status":"error","data":"invalid children order: A child is missing: folder:46"}". What is strange, it keeps re-creating those directories. With every sync trial.

**Comment by marcelklehr** [comment]
@mmalisz This should be fixed in the latest version, now.

**Comment by mmalisz** [comment]
@marcelklehr, I've got yet another issue:
`Cannot map parentId:toolbar_____`
Doesn't matter if I try to push the bookmarks to exsisting root, or if I try to push to a new root.

Also, the browser is Firefox 81.0.2 (64 bit).

**Comment by marcelklehr** [comment]
@mmalisz Could you try deleting everything on the server and starting a sync from scratch in the account settings?

**Comment by mmalisz** [comment]
@marcelklehr, nope, no luck.
I've truncated all the bookmarks tables, the error's still there. It happens for both "/" and "/somename" roots.
However, in case of "/somename", an empty directory is created.

**Comment by mmalisz** [comment]
@marcelklehr, all right, seems to be fine now.
It has started working after instead of trying "sync up" button, I've pressed "sync now".

**Comment by candrapersada** [comment]
Will there be a feature to automatically sync down tabs from WebDAV or Google Drive at browser startup?

**Comment by marcelklehr** [comment]
@candrapersada Not at the moment no.

**Comment by mnalis** [comment]
@candrapersada do note that such feature might likely have a lots of problems, for example off the top of my head:
- browser would have to "hang" on startup (i.e. forbid user to add / remove / modify any tab) until it syncs tabs due to nature of the request (or the synced tabs would be completely wrong, things you started would disappear mid-usage etc.)
- it sync takes long (due to low bandwidth, or high number of tabs, or slow server, etc...) it would mean you're unable to use browser at all for minutes (or longer) after you started it
- if there is a problem with server (server unreachable due to network routing or firewall or server hangup or whatever), you'd likely be unable to use the browser at all (or at least until timeout occurs at e.g. 5 minutes, if you accept that all new tabs that you open from that moment on will be lost in all browsers, including that one, on next startup).
- some of those problems might be partially addressed (for example, cancel button might be shown to abort slow or hanged sync), but then you would have to remember to manually sync tabs before you close the browsers, or all your new changes would be lost (or worse - only partially-synced tabs pushed to server, which would cause all other instances of browser to also lose all those tabs when they start)
- you would be disallowed to ever have more then only one browser opened until all other browsers are closed and have correctly pushed their changes - or you would randomly lose all tabs on all browsers which have not synced correctly. Which for example means that if your browser crashed (or you forcefully closed it without syncing first, or your laptop shutdown due to low battery etc), all tabs on all browsers (including the one which didn't push changes correctly) would be lost (as on startup they would sync changes from server)

IOW I don't think that `pull tabs on startup` would be good idea ever. `merge tabs on startup`, maybe, although even that is dubious and has its problems (e.g. it would be a chore to make sure that the tabs you closed do not reappear on next startup)

**Comment by marcelklehr** [comment]
@mnalis I mostly agree. I think for now the most useful mode is to manually push and pull tabs, unless someone has a better idea on how tab sync could be improved -- please open a new issue in this case, though.

**Comment by candrapersada** [comment]
then how about auto disable tab sync when starting browser?
![image](https://user-images.githubusercontent.com/36833664/158030007-96af16bb-97ba-4c78-a11d-b4363fe3d123.png)

**Comment by marcelklehr** [comment]
That'd be totally unexpected

**Comment by candrapersada** [comment]
is there an option to auto disable tab sync when starting browser,
so that tabs don't disappear from local & cloud when you start opening browsers?
![image](https://user-images.githubusercontent.com/36833664/159113170-acbd15c4-4b44-480e-8159-05084841dc49.png)

**Comment by hellomiakoda** [comment]
How tab syncing works via the built in feature in Vivaldi, for example, is your browser syncs tabs to the cloud - and there is a menu where current tabs are listed per device. I can open that menu, pick a device, and open any tabs from any other device. 
I'd really like to see Floccus work this way - even if it uses a folder in bookmarks (and corrosponding sub folders to do this) instead of it's own menu. With tab sync and bookmark sync combined, this could easily be done by Floccus simply syncing the local tabs to it's corrosponding sub-folder, and the bookmark sync would go ahead and sync that sub folder with the rest of the bookmarks. 

Why not use Vivaldi's built it? I do, for now. But... It doesn't cover other browsers I use, and, more importantly, I'd be much rather having this data on MY server instead of thiers.
