### ISSUE TITLE
Want to update the signed plug-in version

### ISSUE THREAD

**Issue by ixmu** [marcelklehr/floccus#767]
Hope to update the plugin version in the chrome store.
Hope to update the plugin version in the Edge store.
Hope to update the plugin version in theFirefox store.

If you don't have time, I'm happy to help.

**Comment by marcelklehr** [comment]
Hi,
currently Mozilla Addons store has the latest release (v4.4.x), while Chrome and Edge are still on v4.3.x. This is intentional as a lot of issues have transpired in connection with v4.4.x. My goal is to arrive at a new version that resolves the issues in v4.4.x as soon as possible, and, after successful rollout on Firefox, continue rolling out v4.4.x on Chrome and Edge.

This effort has been delayed by me having to take a break the last two months, but I'm back in the game now :)
