### ISSUE TITLE
Make floccus prefix configurable to support multiple "profiles"

### ISSUE THREAD

**Issue by humarf** [marcelklehr/floccus#77]
Hello,

I use floccus 2.0.6, nextcloud 13.0, bookmarks 0.11.0 and chrome 65.

Syncing works fine even with subfolders. Subfolders are converted to tags by floccus. All folder names are prefixed by string "floccus:>" when converted to a tag. Is there a way to switch this off, please?

Thanks and best regards
Martin

**Comment by marcelklehr** [comment]
Hey @humarf 
Thanks for reaching out. Since the user can add arbitrary tags in the bookmarks app on the server, I chose to add a prefix for all floccus-specific tags. I'm not particular about the exact prefix, but it's essential that there is one, I'm afraid. :)
In general, I realize that the solution to sync bookmark paths as tags is not ideal, but it's an upstream issue that needs to be addressed in nextcloud bookmarks. The focus there has been on tags, as the idea is that they can be used more flexibly than folders.

**Comment by humarf** [comment]
Having it configurable would be a good idea. If it's really needed I could switch to a bit less eye catching prefix.

**Comment by marcelklehr** [comment]
@pablohess That's a great idea!

**Comment by marcelklehr** [comment]
You can now configure the server path to sync to in floccus v2.2.0 :)
