### ISSUE TITLE
Tag "floccus" created automatically

### ISSUE THREAD

**Issue by mase76** [marcelklehr/floccus#84]
Hi!
Why is there a tag named "floccus" created automatically?
When I delete it, it will be recreated.

**Comment by sunjam** [comment]
Is it possible to disable the automatic creation of the "floccus" tag?

**Comment by marcelklehr** [comment]
Short explanation: the floccus tag is a combination of `PREFIX` `FOLDER_PATH`. `PREFIX` is floccus: at the moment. The `FOLDER_PATH` used to be a normal path with slashes, e.g. /foo/bar/baz, but nextcloud cannot handle that, so / are replaced with >. So, when you add a bookmark in the root folder floccus adds floccus:>. This is in order to know in which folder the bookmark is when floccus syncs the next time.

**Comment by marcelklehr** [comment]
It is not possible to disable the autmatic creation of this tag, because there is no other way to know in which folder the bookmark is.

**Comment by sunjam** [comment]
Okay, makes sense.  If we cannot delete such tags, it would be nice to be able to hide this tag + the others created as part of internal floccus usage.
