### ISSUE TITLE
Support to sync also "file://" bookmarks

### ISSUE THREAD

**Issue by efelon** [marcelklehr/floccus#87]
### Software versions

* Browser: 
  * Chrome (65.0.3325.181)
  * Firefox (58.0.2)
* Nextcloud: 13.0.1
* Nextcloud Bookmarks app: 0.11.0
* Floccus: 2.0.6

### Steps to reproduce
1. create bookmark as file-url (e.g. file:///c:/temp/test.html)
2. sync
3. check on other instance (regardless of browser)

### Expected outcome
Bookmark should sync like http/https urls.

### Actual outcome
Bookmarks with file-url are ignored. Also folders containing only file-urls are ignored and not synchronised.

**Comment by marcelklehr** [comment]
This is a known issue as nextcloud bookmarks doesn't support file URLs for security reasons.

**Comment by TheDevFreak** [comment]
@marcelklehr Would it be possible for floccus to store `file://` to nextcloud as `filebookmark` so that when floccus syncs it send to nextcloud as `filebookmark` and when it retreives `filebookmark` at the start of a `url` replace it to `file://` on the client? Same could be done for `javascript:` bookmarks with `jsbookmark` ?

**Comment by marcelklehr** [comment]
@TheDevFreak Frankly, that feels like too much of a hack to me. :D The possibility of a WebDAV backend is being explored, however, which should adding support for these URLs much easier. See #86

**Comment by jlbprof** [comment]
I am looking at WebDav which would do what you want, with Nextcloud and for
other servers.

**Comment by marcelklehr** [comment]
This is fixed with the WebDAV adapter in the latest beta version. See #131 :)
