### ISSUE TITLE
Doesnt work?

### ISSUE THREAD

**Issue by roker** [marcelklehr/floccus#9]
I dont consider myself as a stupid user but I am unable to sync anything to owncloud 9.1

I have enabled OC bookmarks plugin and set credentials and url but looks like ffox doesnt do any request to the server. Should there be a sync button or something in firefox, the one added into the toolbar is only offering me to specify the url and credentials but nothing happens except from that. Are there any logs available to see what is going on? Btw, I am running ffox 51, on windows 8.1.

Thank you for creating this add in :)

**Comment by marcelklehr** [comment]
Hi @roker,
You should find a new folder in your bookmarks called "Owncloud". It works like a dropbox for bookmarks.
I'm not sure floccus works with owncloud 9.1, however. I'm testing with nextcloud only, at the moment, and it doesn't work, probably due to changes in nextcloud. However, I'm working with the bookmarks app developers to resolve that issue and release a new version that will allow syncing again, hopefully also fixing your issues in owncloud 9.1.

**Comment by marcelklehr** [comment]
and just fyi, you can debug addons in firefox using the special page `about:debugging` ;)
